spring.application.name=config-server
server.port=8888
spring.profiles.active=git
spring.cloud.config.server.git.uri=https://github.com/bishmie/campusdocs-cloud-configurations.git
spring.cloud.config.server.git.search-paths=platform,services
spring.cloud.config.server.git.clone-on-start=true